site_name: Building an internet connected lighting system

docs_dir: docs

pages:
- ['index.md','Requirements']
- ['2_circuit.md', 'Building the circuit']
- ['3_software.md', 'Writing the software']
- ['4_connectivity.md', 'Adding connectivity']
- ['5_controlling-from-cloud.md', 'Controlling the device with Pelion Device Management']
- ['6_cloud-api.md', 'Using the Device Management API']
- ['7_updates.md', 'Applying firmware updates to the device']
- ['8_conclusion.md', 'Conclusion']

copyright: © Arm Ltd. Copyright 2020 – Pelion IoT Platform
